spring:
  profiles:
    active: pro
  servlet:
    multipart:
      maxFileSize: 100MB
      maxRequestSize: 100MB
  datasource:
      driverClassName: com.mysql.jdbc.Driver
      url: jdbc:mysql://127.0.0.1:3306/patient?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8
      username: root
      password: root
  redis:
    database: 1
    host: 127.0.0.1
    port: 6379
    password: root

mybatisPlus:
  mapperLocations: classpath:**/mapper/xml/*.xml