spring:
  profiles:
    active: pro
  servlet:
    multipart:
      maxFileSize: 100MB
      maxRequestSize: 100MB
  datasource:
      driverClassName: com.mysql.jdbc.Driver
      url: jdbc:mysql://139.186.130.231:3306/patient?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8
      username: root
      password: Myjoyo@202008
  redis:
    database: 1
    host: 39.105.74.194
    port: 6379
    password: ld840401

mybatisPlus:
  mapperLocations: classpath:**/mapper/xml/*.xml